# Site settings
title: Angelica Granados
email: angelicagranadoscampos@gmail.com
description: Realizando ruebas de sintaxis
url: "https://angelicamariagranados-cyber.github.io/Pruebas"
twitter_username: @anguiegranados
github_username:  AngelicaMariaGranados-cyber

# Build settings
markdown: kramdown
